name: habit_tracker_flutter
description: Habit Tracker completo stile Streamlit
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  shared_preferences: ^2.1.1
  fl_chart: ^0.60.0                   # grafici
  flutter_local_notifications: ^14.0.0 # notifiche locali
  percent_indicator: ^4.2.2            # progress bar circolare


dev_dependencies:
  flutter_test:
    sdk: flutter
